##Set working directory and load in data 
data<-read.csv("PbRPress.csv", na.strings="", stringsAsFactors = T)
group<-read.csv("PbRGroups.csv", na.strings="", stringsAsFactors = T)
data<-merge(data, group, by="Subject")

##Rename relevant variables, and remove irrelevant variables 
data<-data[,-c(2:6,13)]
data<-subset(data, Trial>0)
	#Make sure you have validated your data before doing this as it will remove any sessions where someone forgot to insert the session #



##Process a Dataset for all other variables analyses
	library(dplyr)
	library(tidyr)
	#Corrects
		#Count up responses in temp, and merge in with main set
		temp<-aggregate(Correct~Subject+Session+Week+Injury+Cue+Group, sum, data=data)
			#Grab all relevant variables for very first one. Subsequent can just use subject/session
		PbR<-temp
			#Write a dataframe for all this to go to
	#Switches
		temp<-aggregate(Switches~Subject+Session, sum, data=data)
		PbR<-merge(PbR, temp, by=c("Subject", "Session"), all=T)
		PbR$Switches[is.na(PbR$Switches)]<-0
			#Replace any NAs that were generated by new data with 0s
	#Omissions, Total Left, Total Right
		temp<-data %>% count(Choice, Subject, Session)
		temp<-reshape(temp, timevar="Choice", idvar=c("Subject", "Session"), direction="wide")
		colnames(temp)[colnames(temp)=="n.0"] <- "Omissions"
		colnames(temp)[colnames(temp)=="n.1"] <- "TotLeft"
		colnames(temp)[colnames(temp)=="n.2"] <- "TotRight"
		temp$Omissions[is.na(temp$Omissions)]<-0
		PbR<-merge(PbR, temp, by=c("Subject", "Session"), all=T)
	#Reinforcers
		temp<-aggregate(Reinforced~Subject+Session, sum, data=data)
		PbR<-merge(PbR, temp, by=c("Subject", "Session"), all=T)
		colnames(PbR)[colnames(PbR)=="Reinforced"] <- "Reinforcers"
	#Collection Latency
			data$log_Collect_Lat<-log(data$Collect.Lat)
				#Will throw a bunch of infinites for 0, but we want to eliminate 0's anyway
			data$log_Collect_Lat[is.infinite(data$log_Collect_Lat)]<-NA
			temp<-aggregate(log_Collect_Lat~Subject+Session, mean, data=data)
			colnames(temp)[colnames(temp)=="log_Collect_Lat"] <- "logColLat"
			PbR<-merge(PbR, temp, by=c("Subject", "Session"), all=T)
	#Win-Stay
			temp<-aggregate(WinStay~Subject+Session, mean, data=data)
			PbR<-merge(PbR, temp, by=c("Subject", "Session"), all=T)
	#Lose-Shift
			temp<-aggregate(LoseShift~Subject+Session, mean, data=data)
			PbR<-merge(PbR, temp, by=c("Subject", "Session"), all=T)
	#Convert various variables to percents. Create new variables if you want to keep counts
			PbR$PctCorrect<-PbR$Correct/(PbR$TotLeft+PbR$TotRight)*100
			PbR$PctOm<-PbR$Omissions/(200)*100
			PbR$WinStay<-PbR$WinStay*100
			PbR$LoseShift<-PbR$LoseShift*100
			PbR$PctReinf<-PbR$Reinforcers/(PbR$TotLeft+PbR$TotRight)*100
			
#Data Vis
	library(lattice)
	xyplot(Switches~Week|Cue, group=Injury, data=PbR, type="a", lwd=4, auto.key=T)
#	xyplot(PctCorrect~Week|Cue, group=Injury, data=PbR, type="a", lwd=4, auto.key=T)
#	xyplot(PctOm~Week|Cue, group=Injury, data=PbR, type="a", lwd=4, auto.key=T)
#	xyplot(Reinforcers~Week|Cue, group=Injury, data=PbR, type="a", lwd=4, auto.key=T)
#	xyplot(WinStay~Week|Cue, group=Injury, data=PbR, type="a", lwd=4, auto.key=T)
#	xyplot(LoseShift~Week|Cue, group=Injury, data=PbR, type="a", lwd=4, auto.key=T)
#	xyplot(logColLat~Week|Cue, group=Injury, data=PbR, type="a", lwd=4, auto.key=T)
	
#Generate Descriptive stats for easy graphing
	library(plotrix)
	#Switches
		Means<-aggregate(Switches~Injury+Cue+Week, PbR, mean)
		Error<-aggregate(Switches ~ Subject+Injury+Cue+Week, PbR, mean)
		Error<-aggregate(Switches ~ Injury+Cue+Week, Error, std.error)
		colnames(Error)[colnames(Error)=="Switches"] <- "SwitchError"
		temp<-merge(Means, Error, by=c("Injury", "Cue", "Week"), all=T)
	#Corrects
		Means<-aggregate(PctCorrect~Injury+Cue+Week, PbR, mean)
		Error<-aggregate(PctCorrect ~ Subject+Injury+Cue+Week, PbR, mean)
		Error<-aggregate(PctCorrect ~ Injury+Cue+Week, Error, std.error)
		colnames(Error)[colnames(Error)=="PctCorrect"] <- "CorrectError"
		temp<-merge(temp, Means, by=c("Injury", "Cue", "Week"), all=T)
		temp<-merge(temp, Error, by=c("Injury", "Cue", "Week"), all=T)
	#Omissions
		Means<-aggregate(PctOm~Injury+Cue+Week, PbR, mean)
		Error<-aggregate(PctOm ~ Subject+Injury+Cue+Week, PbR, mean)
		Error<-aggregate(PctOm ~ Injury+Cue+Week, Error, std.error)
		colnames(Error)[colnames(Error)=="PctOm"] <- "OmError"
		temp<-merge(temp, Means, by=c("Injury", "Cue", "Week"), all=T)
		temp<-merge(temp, Error, by=c("Injury", "Cue", "Week"), all=T)
	#Reinforcers
		Means<-aggregate(Reinforcers~Injury+Cue+Week, PbR, mean)
		Error<-aggregate(Reinforcers ~ Subject+Injury+Cue+Week, PbR, mean)
		Error<-aggregate(Reinforcers ~ Injury+Cue+Week, Error, std.error)
		colnames(Error)[colnames(Error)=="Reinforcers"] <- "ReinfError"
		temp<-merge(temp, Means, by=c("Injury", "Cue", "Week"), all=T)
		temp<-merge(temp, Error, by=c("Injury", "Cue", "Week"), all=T)
	#WinStay
		Means<-aggregate(WinStay~Injury+Cue+Week, PbR, mean)
		Error<-aggregate(WinStay ~ Subject+Injury+Cue+Week, PbR, mean)
		Error<-aggregate(WinStay ~ Injury+Cue+Week, Error, std.error)
		colnames(Error)[colnames(Error)=="WinStay"] <- "WinStayError"
		temp<-merge(temp, Means, by=c("Injury", "Cue", "Week"), all=T)
		temp<-merge(temp, Error, by=c("Injury", "Cue", "Week"), all=T)
	#LoseShift
		Means<-aggregate(LoseShift~Injury+Cue+Week, PbR, mean)
		Error<-aggregate(LoseShift ~ Subject+Injury+Cue+Week, PbR, mean)
		Error<-aggregate(LoseShift ~ Injury+Cue+Week, Error, std.error)
		colnames(Error)[colnames(Error)=="LoseShift"] <- "LoseShiftError"
		temp<-merge(temp, Means, by=c("Injury", "Cue", "Week"), all=T)
		temp<-merge(temp, Error, by=c("Injury", "Cue", "Week"), all=T)
	#logColLat
		Means<-aggregate(logColLat~Injury+Cue+Week, PbR, mean)
		Error<-aggregate(logColLat ~ Subject+Injury+Cue+Week, PbR, mean)
		Error<-aggregate(logColLat ~ Injury+Cue+Week, Error, std.error)
		colnames(Error)[colnames(Error)=="logColLat"] <- "ColLatError"
		temp<-merge(temp, Means, by=c("Injury", "Cue", "Week"), all=T)
		temp<-merge(temp, Error, by=c("Injury", "Cue", "Week"), all=T)
	write.table(temp, "PbRDescriptives.csv", sep=",", col.names=NA)


#Analysis
library(lmerTest)
library(MuMIn)
library(emmeans)
PbR$Subject<-as.factor(PbR$Subject)
PbR$Injury<-as.factor(PbR$Injury)
PbR$Cue<-as.factor(PbR$Cue)
PbR<-subset(PbR, Week<12)
PbR$LoseStay<-100-PbR$LoseShift

#Initial check for normality to setup transformations.
#library(MASS)
#boxcox(PbR$Switches+0.5~1)
#boxcox(PbR$PctCorrect~1)
#boxcox(PbR$PctOm+0.25~1)  #need to fall back to GLM since it is so zero inflated.
#boxcox(PbR$Reinforcers~1)
#boxcox(PbR$WinStay~1)
#boxcox(PbR$LoseStay~1)
#boxcox(PbR$logColLat~1)

PbR$t.Switch<-log(PbR$Switches+0.5)
PbR$t.LoseStay<-log(PbR$LoseStay)


xyplot(t.Switch~Week|Group, group=Subject, data=PbR, type="a", lwd=4)



PbR$Cue<-relevel(PbR$Cue, ref="None")
PbR$Injury<-relevel(PbR$Injury, ref="Sham")
SwitchModel<-lmer(scale(t.Switch)~Injury*Cue*scale(Week) + (1|Subject), data=PbR)
write.table("Switches", "PbRStats.csv", sep=",", col.names=NA)
write.table(anova(SwitchModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(summary(SwitchModel)$coefficients, "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table("Week Contrasts by Injury/Cue", "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(emtrends(SwitchModel, pairwise~Injury|Cue, var="Week")$contrasts, "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(r.squaredGLMM(SwitchModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(print(VarCorr(SwitchModel), comp=c("Variance", "Std.Dev")), "PbRStats.csv", sep=",", col.names=NA, append=T)

PbR$Cue<-relevel(PbR$Cue, ref="None")
PbR$Injury<-relevel(PbR$Injury, ref="Sham")
OmModel<-glmer(Omissions~Injury*Cue*scale(Week) + (1|Subject), family=poisson, data=PbR)
write.table("Omissions", "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(anova(OmModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(summary(OmModel)$coefficients, "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(r.squaredGLMM(OmModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(print(VarCorr(OmModel), comp=c("Variance", "Std.Dev")), "PbRStats.csv", sep=",", col.names=NA, append=T)

PbR$Cue<-relevel(PbR$Cue, ref="None")
PbR$Injury<-relevel(PbR$Injury, ref="Sham")
WinStayModel<-lmer(scale(WinStay)~Injury*Cue*scale(Week) + (1|Subject), data=PbR)
write.table("Win-Stay", "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(anova(WinStayModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(summary(WinStayModel)$coefficients, "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(r.squaredGLMM(WinStayModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(print(VarCorr(WinStayModel), comp=c("Variance", "Std.Dev")), "PbRStats.csv", sep=",", col.names=NA, append=T)

PbR$Cue<-relevel(PbR$Cue, ref="None")
PbR$Injury<-relevel(PbR$Injury, ref="Sham")
LoseStayModel<-lmer(scale(LoseStay)~Injury*Cue*scale(Week) + (1|Subject), data=PbR)
write.table("Lose-Stay", "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(anova(LoseStayModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(summary(LoseStayModel)$coefficients, "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(r.squaredGLMM(LoseStayModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(print(VarCorr(LoseStayModel), comp=c("Variance", "Std.Dev")), "PbRStats.csv", sep=",", col.names=NA, append=T)

PbR$Cue<-relevel(PbR$Cue, ref="None")
PbR$Injury<-relevel(PbR$Injury, ref="Sham")
CorModel<-lmer(scale(PctCorrect)~Injury*Cue*scale(Week) + (1|Subject), data=PbR)
write.table("Percent Correct", "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(anova(CorModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(summary(CorModel)$coefficients, "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(r.squaredGLMM(CorModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(print(VarCorr(CorModel), comp=c("Variance", "Std.Dev")), "PbRStats.csv", sep=",", col.names=NA, append=T)

PbR$Cue<-relevel(PbR$Cue, ref="None")
PbR$Injury<-relevel(PbR$Injury, ref="Sham")
ReinfModel<-lmer(scale(Reinforcers)~Injury*Cue*scale(Week) + (1|Subject), data=PbR)
write.table("Reinforcers", "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(anova(ReinfModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(summary(ReinfModel)$coefficients, "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(r.squaredGLMM(ReinfModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(print(VarCorr(ReinfModel), comp=c("Variance", "Std.Dev")), "PbRStats.csv", sep=",", col.names=NA, append=T)

PbR$Cue<-relevel(PbR$Cue, ref="None")
PbR$Injury<-relevel(PbR$Injury, ref="Sham")
LatencyModel<-lmer(scale(logColLat)~Injury*Cue*scale(Week) + (1|Subject), data=PbR)
write.table("Collect Latency", "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(anova(LatencyModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(summary(LatencyModel)$coefficients, "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(r.squaredGLMM(LatencyModel), "PbRStats.csv", sep=",", col.names=NA, append=T)
write.table(print(VarCorr(LatencyModel), comp=c("Variance", "Std.Dev")), "PbRStats.csv", sep=",", col.names=NA, append=T)

